name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  JDK_JAVA_OPTIONS: "--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    # Docker actions only work on linux
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, windows-latest, macos-latest]
    #     java-version: [8, 11, 17]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "adopt"
      - name: Install
        run: |
          cd code
          mvn --batch-mode install
  deploy:
    if: github.ref == 'refs/heads/master' && github.repository_owner == 'Codeforces'
    needs: test
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Deploy
        run: |
          cd code
          mvn --batch-mode deploy
